version: "2"

services:
  edge:
    container_name: edge.example.com
    hostname: edge.example.com
    user: testuser
    entrypoint: sleep infinity
    build:
      context: .

  nn:
    ports:
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
    container_name: nn.example.com
    hostname: nn.example.com
    user: root
    entrypoint: /tmp/startup/start-namenode.sh
    build:
      context: .

  dn1:
    container_name: dn1.example.com
    hostname: dn1.example.com
    depends_on:
      - nn
    user: root
    entrypoint: /tmp/startup/start-datanode.sh
    build:
      context: .
