version: "2"

services:
  edge:
    container_name: edge.example.com
    hostname: edge.example.com
    user: testuser
    command: /etc/startup/start-edgenode.sh
    build:
      context: .

  nn:
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
    container_name: nn.example.com
    hostname: nn.example.com
    user: root
    command: /etc/startup/start-namenode.sh
    build:
      context: .

  dn:
    ports:
      - 50075:50075  # DN webui
      - 8042:8042    # NM webui
    container_name: dn.example.com
    hostname: dn.example.com
    depends_on:
      - nn
    user: root
    command: /etc/startup/start-datanode.sh
    build:
      context: .
