version: "2"

networks:
  default:
    driver: bridge

services:
  master:
    user: root
    command: supervisord -c /etc/nn-kerb.supervisord.conf
    build:
      context: .
    hostname: master
    domainname: example.com
    networks:
      default:
        aliases:
          - master.example.com
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
      - 88:88        # Kerberos
      - 749:749      # Kerberos

  worker:
    user: root
    command: supervisord -c /etc/dn-kerb.supervisord.conf
    build:
      context: .
    hostname: worker
    domainname: example.com
    networks:
      default:
        aliases:
          - worker.example.com
    ports:
      - 50075:50075  # DN webui
      - 8042:8042    # NM webui

  edge:
    user: root
    command: supervisord -c /etc/edge-kerb.supervisord.conf
    build:
      context: .
    hostname: edge
    domainname: example.com
    networks:
      default:
        aliases:
          - edge.example.com
