version: "2"

services:
  nn:
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
    container_name: nn.example.com
    hostname: nn.example.com
    user: root
    command: supervisord -c /etc/nn.supervisord.conf
    build:
      context: .

  dn:
    ports:
      - 50075:50075  # DN webui
      - 8042:8042    # NM webui
    container_name: dn.example.com
    hostname: dn.example.com
    user: root
    command: supervisord -c /etc/dn.supervisord.conf
    build:
      context: .

  edge:
    container_name: edge.example.com
    hostname: edge.example.com
    user: root
    command: supervisord -c /etc/edge.supervisord.conf
    build:
      context: .
